### ISSUE TITLE
charmhelpers harden for suid_guid uses mlocate which may not always be installed

### ISSUE THREAD

**Issue by ajkavanagh** [juju/charm-helpers#179]
This is from: https://bugs.launchpad.net/charm-ceph-osd/+bug/1759145

Essentially, charmhelpers ought to check if it is available and complain/log/try to install it?  (who knows what the package would be called if it's not an ubuntu minimal).

Relevant line:

```bash
charmhelpers/contrib/hardening/host/checks/suid_sgid.py
57:             '/usr/bin/mlocate',
```

**Comment by wolsen** [comment]
Actually, from the traceback in lp#1759145 it looks like it stems from the fact that the ceph-osd charm's config-changed hook makes a call into charmhelpers.core.host.add_to_updatedb_prunepath [0] which attempts to read the /etc/updatedb.conf file.

It seems like the appropriate thing here would be to raise an issue against the charm-helpers library to check the file exists prior attempting to read the file (or simply handle the error when it doesn't exist).

[0] - https://github.com/openstack/charm-ceph-osd/blob/master/hooks/ceph_hooks.py#L399
