### ISSUE TITLE
Does config('prefer-ipv6') retrieve option from model config?

### ISSUE THREAD

**Issue by quulah** [juju/charm-helpers#26]
I'd like to access the model configuration prefer-ipv6 from our charms. contrib.network.ip uses this, but I'm not sure if it works: https://github.com/juju/charm-helpers/blob/master/charmhelpers/contrib/network/ip.py#L582

Setting model-config to true or false either gets me None, or when accessing the config dict, a KeyError. And if I have understood correctly, hookenv.config() should read the config.yaml of the charm.

Is there some kind of mix up with the OpenStack charms, as they seem to have a separate prefer-ipv6 option, or is my Juju version too old to support this? 

https://github.com/openstack/charm-openstack-dashboard/blob/master/config.yaml#L238

Currently at 2.0 still.

**Comment by quulah** [comment]
This Launchpad issue: https://bugs.launchpad.net/charms.openstack/+bug/1704334 is about some overlab between openstack helpers and the more generic ones, so that got me thinking that perhaps it doesn't work with anything other than charms with a prefer-ipv6 option in config.yaml.

**Comment by quulah** [comment]
If there's any other way to get model config from the charms, I'll be happy to hear about it.

**Comment by ajkavanagh** [comment]
@quulah The `hookenv.config()` function retrieves values for the application (i.e. charm 'instance') which are defined in the `config.yaml` file in the charm.  i.e. those values that can be set and retrieved using:

```bash
juju config <application> key=value key2=value2
```

As far as I know, there's no way to access the *model-config* from within charm code (i.e. that you set with:)

```bash
juju model-config model-key=value ...
```

In the OpenStack charms we the `prefer-ipv6` config option is defined in the charms' `config.yaml` file.  Hope that helps.

**Comment by quulah** [comment]
@ajkavanagh Yeah, that's pretty much what I thought. I can work around the limitation.

But isn't there a situation now, where the generic `charmhelpers.contrib.network.ip` won't work with _any_ charm? `get_relation_ip()` will call `config('prefer-ipv6')`, so it assumes that the charm will have that option.

Works with the OpenStack charms, but will require any other charm to have the same option. This is okay, but it should probably be documented in some way. :)

Any way, thanks for the answer. I'll close this issue, as I don't think there's anything to be done here.

**Comment by quulah** [comment]
@javacruft Yeah, that's actually true.
