### ISSUE TITLE
Docs on pythonhosted.org are out of date, stuck on v0.12.0

### ISSUE THREAD

**Issue by szeestraten-ntnu** [juju/charm-helpers#27]
The docs on https://pythonhosted.org/charmhelpers/ seem to be pretty out of date with the title displaying v0.12.0.

**Comment by johnsca** [comment]
pythonhosted.org has been deprecated and we need to get this repo set up on RTD.io.

**Comment by johnsca** [comment]
@javacruft I don't have access GitHub privs to set this up, so it's down to you.  ;)

**Comment by szeestraten** [comment]
Great. Y'all should also either redirect the pythonhosted site or take it down to avoid confusion.

**Comment by szeestraten-ntnu** [comment]
Calling Mr. @javacruft. It would be really nice to have some up to date docs.

**Comment by szeestraten-ntnu** [comment]
Ping @javacruft
