### ISSUE TITLE
update to apt_install within charmhelpers.contrib.openstack.utils breaks with layer-basic use_venv=true

### ISSUE THREAD

**Issue by afreiberger** [juju/charm-helpers#364]
We are seeing an issue with 'import netifaces' after apt_install("python3_netifaces", fatal=True) is called from the charmhelpers.contrib.network.ip module during a charm install hook where we are importing functions from charmhelpers.contrib.openstack.utils.

```
unit-openstack-service-checks-0: 21:33:03 INFO unit.openstack-service-checks/0.juju-log Installing python3-netifaces with options: ['--option=Dpkg::Options::=--force-confold']
unit-openstack-service-checks-0: 21:33:03 DEBUG unit.openstack-service-checks/0.install Reading package lists...
unit-openstack-service-checks-0: 21:33:03 DEBUG unit.openstack-service-checks/0.install Building dependency tree...
unit-openstack-service-checks-0: 21:33:03 DEBUG unit.openstack-service-checks/0.install Reading state information...
unit-openstack-service-checks-0: 21:33:04 DEBUG unit.openstack-service-checks/0.install python3-netifaces is already the newest version (0.10.4-0.1build4).
unit-openstack-service-checks-0: 21:33:04 DEBUG unit.openstack-service-checks/0.install 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
unit-openstack-service-checks-0: 21:33:04 DEBUG worker.uniter.jujuc running hook tool "juju-log"
unit-openstack-service-checks-0: 21:33:04 ERROR unit.openstack-service-checks/0.juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-openstack-service-checks-0/.venv/lib/python3.6/site-packages/charmhelpers/contrib/network/ip.py", line 39, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'
```

You can see the full traceback from install hook on cs:~canonical-bootstack/openstack-service-checks-25 here: https://pastebin.ubuntu.com/p/bYhkbsjDbH/

This charm was previously compiled against charmhelpers==0.19.1 and worked fine, but now with charmhelpers==0.20.1, it appears apt_install functions are installing the package in the system locations, but the newly installed module is not available within the charm venv.

I believe the commit to blame may be this:
https://github.com/juju/charm-helpers/commit/d2ea1b8d8c2fb5bc80b8ff2f7f81c82a02bd611b#diff-935a00f40074c3c59d617c88f71e42ef

You can see a working version of nearly identical code with charmhelpers 0.19.1 at cs:~canonical-bootstack/openstack-service-checks-24

**Comment by fnordahl** [comment]
A recent [update](https://github.com/juju-solutions/layer-basic/pull/135) to ``layer-basic`` has flipped the default of ``include-system-packages`` to False.

With that set you would need to include your charm dependencies in its ``wheelhouse.txt`` moving forward.  If you're not ready for it yet you can always revert to the previous default for your charm by updating its layer.yaml.

**Comment by fnordahl** [comment]
Just as a reference for future travelers some background information for the change and a heads up was [posted](https://discourse.jujucharms.com/t/heads-up-change-of-default-in-layer-basic/1562/) on the [Juju Discourse](https://discourse.jujucharms.com/) page a while back.

**Comment by afreiberger** [comment]
Actual issue is that layer-basic changed use_system_packages=false 14 days ago:

https://github.com/juju-solutions/layer-basic/commit/df309d4071d44a9b6a68c19b244ab72a69cee8ef

It seems inconsistent for layer-basic to auto-include charmhelpers in wheelhouse which uses techniques such as try: import x; except: apt_install(x); import x, and yet set include_system_packages = false.
