### ISSUE TITLE
Allow custom environment for jinja templates

### ISSUE THREAD

**Issue by chris-sanders** [juju/charm-helpers#367]
Jinja allows for several customization options when creating the environment to processes templates. Specifically being able to change the start/end characters for variables and blocks is needed when processing templates of templates and should be exposed in the template module.

**Comment by mkalcok** [comment]
(@chris-sanders) I think that with successful merge of #592 . This issue can be closed.

**Comment by auria** [comment]
@ajkavanagh FYI, I think this issue can be closed. A PR was merged a few back, thanks!

**Comment by ajkavanagh** [comment]
As advised by @auria I'm closing this issue.
