### ISSUE TITLE
Jinja2==2.11 is not installed with layer-basic

### ISSUE THREAD

**Issue by xavpaice** [juju/charm-helpers#433]
Since commit juju/charm-helpers@2e65842 we need 2.11 in order to install/upgrade charms, but the wheelhouse.txt in layer-basic specifies Jinja2<=2.10.1.

Not sure if this is simply that wheelhouse.txt needs an update, or if charmhelpers needs a fix, will report in both places.

**Comment by fnordahl** [comment]
This is most likely due to a mismatch between the build environment and the deploy environment.

That mismatch will always be there so I think the changes to the setup and requires files in the referenced commit, while with good intention, does not actually work in practice.

Perhaps @addyess would want to take a look and perhaps revert that part of the change?

**Comment by auria** [comment]
I have tested with the cs:ubuntu charm, which uses layer-basic to install default python libs.

Indeed, this issue happens because cs:ubuntu had "charm build" run from a machine with a py3 version >=3.4 (not a trusty machine).

charmhelpers is forcing (ie. in bionic) Jinja2==2.11 but lower versions should be allowed. I've pushed a MR and testing passed.

See https://github.com/juju/charm-helpers/pull/434

**Comment by auria** [comment]
BTW, the issue can be reproduces by running:

```
for SERIES in trusty xenial bionic;do
juju deploy --series $SERIES cs:ubuntu ubuntu-${SERIES}
done
```
By running the above, the `install` hook will fail in trusty and xenial.

**Comment by auria** [comment]
The issue has also been filed as affecting charms such as https://bugs.launchpad.net/telegraf-charm/+bug/1863962

**Comment by addyess** [comment]
i might be able to upload a *new* change, but revert is no good.  

Previously the `setup.py` listed just "Jinja2" with no pinning at all.  That just means, it would follow the tip of that library wherever it might go.  

Perhaps the easiest solution at this point is to pin to `Jinja2==2.10` which currently holds the broadest support from py27 -> py38.

```
> python3 -m virtualenv -p python3 venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1090: DeprecationWarning: the imp module is New python executable in /home/ubuntu/venv/bin/python3
Also creating executable in /home/ubuntu/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
> source venv/bin/activate
(venv) > pip install Jinja2==2.10
Collecting Jinja2==2.10
  Downloading Jinja2-2.10-py2.py3-none-any.whl (126 kB)
     |████████████████████████████████| 126 kB 2.0 MB/s 
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Installing collected packages: MarkupSafe, Jinja2
Successfully installed Jinja2-2.10 MarkupSafe-1.1.1
(venv) > python
Python 3.8.2rc1 (default, Feb 12 2020, 00:06:56) 
[GCC 9.2.1 20200203] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> jinja2.__version__
'2.10'
>>> 
```

```
> python3 -m virtualenv -p python2 venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/addyess/venv/bin/python2
Also creating executable in /home/addyess/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
> source venv/bin/activate
(venv) > pip install Jinja2==2.10
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting Jinja2==2.10
  Using cached Jinja2-2.10-py2.py3-none-any.whl (126 kB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp27-cp27mu-manylinux1_x86_64.whl (24 kB)
Installing collected packages: MarkupSafe, Jinja2
Successfully installed Jinja2-2.10 MarkupSafe-1.1.1
(venv) > python
Python 2.7.17 (default, Jan 21 2020, 23:28:51) 
[GCC 9.2.1 20200117] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jinja2
>>> jinja2.__version__
'2.10'
>>> 
```

**Comment by fnordahl** [comment]
Having anything pinned at a specific version is asking for issues like this, especially for a library that is so widely used.

There is lots of room in individual layers and charms for authors to do the pinning themselves if they wish.

Given this has caused issues for several people I would suggest revert until we figure out the best solution.

**Comment by xavpaice** [comment]
the release of charm-helpers 0.20.10 includes this fix - thanks for the swift response!
