### ISSUE TITLE
Missing openstack release name support in get_os_codename_install_source

### ISSUE THREAD

**Issue by wolsen** [juju/charm-helpers#665]
Commit 5c377025 added support for specifying simply the OpenStack release name as an installation source, however the charmhelpers.contrib.openstack.utils.get_os_codename_install_source does not support the bare OpenStack release name which prevents the neutron-api charm from installing when configured as such.

**Comment by ajkavanagh** [comment]
This should be pretty easy to fix; I'll rustle up something.
