### ISSUE TITLE
SelectableGroups dict interface is deprecated. Use select.

### ISSUE THREAD

**Issue by hloeung** [juju/charm-helpers#702]
Hi,

Seeing these warnings now:

`.tox/unit/lib/python3.10/site-packages/charms/reactive/relations.py:125`
`  /tmp/tmpfiles-hloeung/tmp/smtp-relay/.tox/unit/lib/python3.10/site-packages/charms/reactive/relations.py:125: DeprecationWarning: SelectableGroups dict interface is deprecated. Use select.`
`    for ep in entry_points().get('charms.reactive.relation_factory', []):`

**Comment by ajkavanagh** [comment]
That doesn't appear to be in `charm-helpers`? Are you thinking of [charms.reactive](https://github.com/juju-solutions/charms.reactive)?

**Comment by hloeung** [comment]
Oh yes, sorry - https://github.com/juju-solutions/charms.reactive/issues/237
