### ISSUE TITLE
PR#58 breaks cert-file comparisons as one is binary and the other is text

### ISSUE THREAD

**Issue by ajkavanagh** [juju/charm-helpers#86]
Due to the PY3 changes in PR #58 the switch from text to binary has broken usage in charms.

We could easily to revert to just using unicode strings rather than writing in binary and then it ought to work fine.  However, would need to check that it actually works in, say, neutron-api charm first.

**Comment by tbaumann** [comment]
Ping.
Still affecting pretty much all openstack charms and randomly breaking ssl connections due to constant re-writing of the file.


This fixes it. Just open the file in binary.
```
def retrieve_ca_cert(cert_file):
    cert = None
    if os.path.isfile(cert_file):
        with open(cert_file, 'rb') as crt:
            cert = crt.read()
    return cert
```

**Comment by tbaumann** [comment]
Oh, looks like we just missed the 18.02 OpenStack charm release window.
I guess I would have pushed harder, had I thought about that release window. :smile:

**Comment by ajkavanagh** [comment]
So this is now a bigger issue, and (I think) has triggered this [bug](https://bugs.launchpad.net/charm-neutron-api/+bug/1762431) on the neutron-api charm when it switched to py3.

**Comment by tbaumann** [comment]
Yea, no kidding. I'm surprised this didn't cause more of a fuzz yet. :wink: 

I have hot fixed versions of the following charms in our environments to avoid random api errors.

- ceph-radosgw
- cinder
- cinder-ceph
- glance
- hacluster
- heat
- keystone
- memcached
- nova-cloud-controller
- nova-compute
- openstack-dashboard
- neutron-api

**Comment by ajkavanagh** [comment]
We'll get this fixed and do a stable backport too.  Thanks for the list, too!

**Comment by thedac** [comment]
Here is the change for charmhelpers:
https://github.com/juju/charm-helpers/pull/146

The individual charms will need to be checked as well. That will be tracked in 
https://bugs.launchpad.net/charm-neutron-api/+bug/1762431

Keystone, in particular, will also need verification of its certificate handling for when it goes PY3.

**Comment by ajkavanagh** [comment]
#146 fixed this bug, so closing.
